### ISSUE TITLE
DOI issue

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#114]
@jdeck88 arks are not resolving-- see https://amphibiandisease.org/projects/?id=286
they should be pointing to the Ampihbian Disease project page
Can you fix? (I thought we had already fixed these so did something happen?) 

Also, related: The project page link should prepend ```https://n2t.net/``` too. (@birbjam task?)

**Comment by jdeck88** [comment]
That one looked like it was not ever fixed on EZID. (i had to login to EZID and change all the legacy projects manually earlier).    So, that is fixed now.

Also, the project page link just takes the EZID as presented on GEOME.. i updated that project to read properly as https://n2t.net/ark:/21547/Cyo2
