### ISSUE TITLE
https://amphibiaweb.org/amphib_names.json throws a json error

### ISSUE THREAD

**Issue by birbjam** [BNHM/AmphibiaWebDiseasePortal#115]
There is possibly a json formatting error - missing comma, inconsistent quotations, etc. that is preventing this data from being fetched.
Error in developer console reads: `SyntaxError: Unexpected token  in JSON at position 1932332`

Once this is fixed, uncomment code related to the function `getTxtData` and `BuildSpeciesDetail` where Common Name, IUCN status, order, and family is being fetched and displayed.

**Comment by JoyceGross** [comment]
This is fixed. There was a junk character entered into one of the common name fields. I removed it.

**Comment by birbjam** [comment]
Thanks Joyce! Looks good
