### ISSUE TITLE
change label on project view

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#118]
There's been confusion as to the buttons on the project detail view. Please change the first button 'Query dataset in Geome' to 'Map dataset in Geome' (see screenshot below)

![Firefox_Screenshot_2021-03-31T07-13-18 937Z](https://user-images.githubusercontent.com/2523089/113105196-2bcf1880-91b6-11eb-850d-ce4bb3bd58d5.png)

I think this may be the main place to find this function so should be more clear.

**Comment by birbjam** [comment]
Done in dev, will update to prod today
