### ISSUE TITLE
static pointers to array position in dashboard.js

### ISSUE THREAD

**Issue by jdeck88** [BNHM/AmphibiaWebDiseasePortal#129]
Referencing values for bd/bsal use static pointers to array position.  See comment from recent commit https://github.com/BNHM/AmphibiaWebDiseasePortal/commit/c647bde28779630af0952b24891d9d0badef7bd8

The return value of Bd and Both reference "NO_CONFIDENCE" array values instead of "TRUE". this was hard to tell since references pointed to array position [0/1] instead of actual value.  This commit is a temporary fix to point to TRUE for these instances but code should be fixed later... i will make an issue for this.

**Comment by birbjam** [comment]
I will take a look!
@jdeck88 do you know which json this is fetching from?

**Comment by birbjam** [comment]
Ok so it's fetching from here.
https://github.com/BNHM/AmphibiaWebDiseasePortalAPI/blob/master/data/diseaseDetected_Bd.json

@mkoo how should this be displayed?

**Comment by jdeck88** [comment]
instead of:
 <td>${bothDetectedValue[2]}</td>
something like:
 <td>${bothDetectedValue['TRUE']}</td>

not sure if huge/javascript uses associative arrays, but you get the point.   array position 2 can't reliably be mapped to that position on the array indicating TRUE

John

**Comment by birbjam** [comment]
Ok that's for True and False, what about the other two: Unknown and No_Confidence? Should I omit those from the table or no?

**Comment by jdeck88** [comment]
I think a good idea to put those in the table as well... that way all the numbers should add up and good to show the users that this data exists..  we could always comment out those rows later if Michelle doesn't want to see them but better to have everything add up rather than have mysteriously missing data.

**Comment by mkoo** [comment]
Agreed. the two values-- unknown and no_confidence-- do have slightly
different connotations. Let the user decide to keep or filter out

**Comment by birbjam** [comment]
Great, I'll set it up.
