### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by birbjam** [BNHM/AmphibiaWebDiseasePortal#18]
Be able to filter data by:
Totals:
- [x] All countries
- [x] All samples
- [x] All species

By:
- [x] Project
- [x] Pathogen type (bd, bsal or both)

Display:
- [x] Positive & Negative Results
- [x] Country

**Comment by jdeck88** [comment]
See #22 - we now have some data to work with ... We'll have to strategize the best ways to build the back-end index... it all depends on the queries we want and we'll need to get more specific on what those are. For now, we just have country, diseaseDetected, yearCollected, and genus for ALL projects.

**Comment by jdeck88** [comment]
I have, i think, all of the tables built that we need to replicate the functionality of the current ad portal site with the exception of species-specific lookups.  Note that this only uses public data.  

One other thing... chartjs requires structuring JSON in a particular way to render the chart.  The old AD portal API delivered content straight to the browser for consumption by chartjs... all the colors and chart specifics were returned by the API.  The new API does not do this... it instead delivers JUST data and leaves it up to the client to the render the chart.  From what i know of D3 and chartjs, i think it will be easier to use D3 to draw the charts D3 typically you specify the data structure and styling separately.  ChartJS does not do this (at least from the little i know of it).  These are just my thoughts...
