### ISSUE TITLE
Create Dashboard Index

### ISSUE THREAD

**Issue by jdeck88** [BNHM/AmphibiaWebDiseasePortal#22]
Create an index in geome for the dashboard to operate.  #18 is dependent on this issue

**Comment by jdeck88** [comment]
Start of dashboard index located here, see new API repo!:

https://github.com/BNHM/AmphibiaWebDiseasePortalAPI/tree/master/data

for now, can call raw data in that directory like:
https://raw.githubusercontent.com/BNHM/AmphibiaWebDiseasePortalAPI/master/data/country.json

This is pulling on ALL public data in GEOME.

**Comment by jdeck88** [comment]
done, see https://github.com/BNHM/AmphibiaWebDiseasePortalAPI

**Comment by mkoo** [comment]
this looks excellent!
