### ISSUE TITLE
formatting on Contribute Data page

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#25]
On https://amphibiandisease-develop.netlify.com/contributing/
the text runs to the edge of page, sometimes cut off in smaller screens. Can the main content be put in a ```<div>``` with more padding on the left and right (or similar way of formatting main content of page? Not sure if this is specific to this Hugo theme but Futres Hugo version has a better format (for example: https://futres.org/how/)

**Comment by birbjam** [comment]
Can you get some screenshots?
I just checked it on my phone and with various screen sizes in DevTools and it looks fine.

**Comment by mkoo** [comment]
![Firefox_Screenshot_2020-04-08T19-29-03 529Z](https://user-images.githubusercontent.com/2523089/78825284-8d3e1c00-7994-11ea-80b6-6ca08b0c4646.png)

This random screenshot goes to the edge of my browser window-- if I look at it on my phone the sentence gets cut off on the right. 
this page looks much nicer:https://amphibiandisease-develop.netlify.com/about/
maybe the images need to be reined in (eg., width=80%)

**Comment by mkoo** [comment]
looks good!
closing
