### ISSUE TITLE
Can private project metadata be viewable?

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#28]
Can we make all project metadata viewable (i.e. public) even if data is private? That is the default on the Disease portal 1.0

in 2.0, on private projects, data links would be disabled so only title, abstract, PI, Contact, but no dataset info would be shown. 

Is this something that Geome-db users also want?

**Comment by jdeck88** [comment]
This was implemented in GEOME production just today. see https://github.com/biocodellc/geome-ui/issues/452
Goto project settings (as administrator) and set discoverable to True... this will return project metadata in the JSON api call for project stats.

**Comment by birbjam** [comment]
@mkoo let me know when these projects are set as discoverable and I will add them to the projects list/table.
