### ISSUE TITLE
Home page updates

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#3]
New splash page for Home looks good!
Header:
Need to update navbar menu order to reflect the big button order better. Suggested menu of header:
Query | Dashboard | Contribute | Projects | Blog

Footer: 
Diana to fix into 3 columns and reorder some of the links, adding Geome as a Resource link, maybe adding a new category **For Developers** which has Github, Documentation
Other suggestions: change footer section to a different color (but I realize that some options may not look good with the logo so let me know if you want a grayscale version)

**Comment by birbjam** [comment]
Header: done

Footer: done except for the positioning of it. Something in the default theme is preventing me from doing what I need it to do.

**Comment by mkoo** [comment]
A few random comments about the footer:
I like the logo flush right (as before). It then balances the logo at the top left in header.
Speaking of the logo, can either one (header or footer) be made larger?
The categories (Learn More, Contact, Add'l Resources, For Developers) need to be in bold or another color as the gray makes it impossible to see them. 
thanks!
