### ISSUE TITLE
Histogram of project datasets not displaying

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#42]
I like the new spot for the project dataset graphs on the Project pages but they seem broken now?
There is only a blank spot for where the histogram would be.
EXAMPLE: https://amphibiandisease-develop.netlify.app/projects/?id=255
(browser: FF and Chrome, MacOSX) 
The page is returning a JSON.parse syntax error to boot.

**Comment by birbjam** [comment]
Yeah I just found the problem. There's a typo on the API side for one dataset that threw everything off. All except for project #286 should be displaying chart now.

**Comment by mkoo** [comment]
looks good!
