### ISSUE TITLE
Instruction Steps ordered-number fail

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#43]
Just tried to follow directions and noticed that the numbered steps somehow re-ordered starting from 3 at step 5 (see screen grab below)

![Firefox_Screenshot_2020-05-19T21-45-19 475Z](https://user-images.githubusercontent.com/2523089/82381812-ac8e8700-99df-11ea-9618-f1d79a137ecf.png)

After 5, should be step 6, etc. This would then make the next section on Generating Templates make sense since it references "Step 7-10"

There's probably some mismatched ```</ol>``` tag somewhere....

**Comment by birbjam** [comment]
huh. Another weird Firefox anomaly. Displays correctly in Chrome but not in FF

**Comment by mkoo** [comment]
I guess I need a tag for FF weirdness!
thx
