### ISSUE TITLE
List By Species: portal stats

### ISSUE THREAD

**Issue by birbjam** [BNHM/AmphibiaWebDiseasePortal#47]
- [x] Add portal stats: create a page with the scientific name in the url that will display the following: 
  - [x] Pie chart for Bd Detected
  -[ ] Display 'No data found when no Bd or Bsal data is availaible.
  - [x] Pie chart for Bsal Detected
  - [ ] Common Name
  - [x] List of projects that determined the result
  - [x] Link to AmphibiaWeb
- [x] Detail project page: clicking on 'samples collected' histogram bars redirects to that species detail page.
- [x] Then add a link to portal stats on the tables as well.

**Comment by mkoo** [comment]
:thumbsup:
