### ISSUE TITLE
Query page: allow user to close message

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#51]
Any way to close the large div at the top of the Query page? it takes a lot of real estate!

**Comment by mkoo** [comment]
The Query page is blank in FF-- screenshot from https://amphibiandisease.org/query/ below. A way to close the message might help

![Firefox_Screenshot_2020-05-27T15-10-35 458Z](https://user-images.githubusercontent.com/2523089/83038378-bd4b8800-9ff1-11ea-8104-8fa50d04a18f.png)

**Comment by birbjam** [comment]
Okay so I just opened it in FireFox as well as in a private window and also had a friend download FireFox to check it out on his end and it was working on all three tries. I'm not quite sure how to fix that.
I'll change the heading message though.

**Comment by mkoo** [comment]
hmm, ok working now-- maybe a FF blocker?  I will investigate. Maybe just reduce the white space around the message so we have more of the query interface??

**Comment by birbjam** [comment]
I reduced the white space around the top and removed the Heading since it was taking up too much space. Just the message is left, I think it looks better now

**Comment by mkoo** [comment]
i agree!
pls push to master
