### ISSUE TITLE
Genus, species capitalization in Chart list

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#53]
Probably a data issue or API but ultimately affects Dashboard interface:
https://amphibiandiseaseportal.netlify.app/dashboard/#sort-t
Shows that Taricha granulosa (correct caps) also has Taricha Granulosa (need specificepithet to be lower case)

there may be others, too.

**Comment by birbjam** [comment]
Yeah this is how it is coming in from the API. We can open an issue there to get that addressed.

**Comment by mkoo** [comment]
OK thanks to cap sensitive Query field, I figured out which project and reloaded with correct capitalization. Will follow up to see if it can be added to the validation rules.
Closing!
