### ISSUE TITLE
Google analytics not working

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#69]
I saw the merge commit that it was added and the UA code looked correct but there still has been no hits for the over 10 days so needs to be checked out.

**Comment by birbjam** [comment]
can you give me the info for where you're tracking this so I can take a look at it?

**Comment by mkoo** [comment]
just invited you to google analytics account for the portal (look out for email)

**Comment by birbjam** [comment]
Done. Realtime active users displaying correctly.

**Comment by mkoo** [comment]
great!
now I can track all three of us! (kidding...)
