### ISSUE TITLE
Downloaded file on project page incomplete

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#71]
Bug report: for a test, go to https://amphibiandisease.org/projects/?id=286 and compare file downloaded from here (```Download Newest file```) with the file on the Geome site https://geome-db.org/workbench/project-overview?projectId=286

I will try other projects but so far the file on the ADP site has over half of the data missing.

**Comment by birbjam** [comment]
Should the contents of the download of "Download Newest Data File" in ADP and "Project CSV Archive" in GEOME be essentially the same ?

**Comment by mkoo** [comment]
For now, I suppose so.
But in the future there will be more than one CSV per project so ideally
the ADP will allow the entire project archive to be downloaded (ie. more
than one expedition file).

So as  a short term fix, this makes sense. For longterm,  I'd like to see
what John provides in terms of Team data downloads since then we could
possibly filter on project id
MK

**Comment by mkoo** [comment]
update?
short answer to your question @birbjam : yes please!

**Comment by jdeck88** [comment]
Here is the current link that the AD portal uses to download data:
```https://api.geome-db.org/records/Sample/excel?networkId=1&q=_projects_:255```

We need to tell the download link to include diagnostic data also, so use this download link:
```https://api.geome-db.org/records/Event/excel?networkId=1&q=_projects_:255+_select_:%5BSample,Diagnostics%5D+```

We did fix an issue with the downloading also on GEOME side.  Once you change the call to specify the entities to select (sample & diagnostics) it will work.  Specify samples + child-most node gets all data (including events)

John

**Comment by birbjam** [comment]
okay I think replacing the link did the trick. 
i'll push to develop, if @mkoo you want to take a look?
i compared the geome download to the project page download and they appear to have the same info.

**Comment by mkoo** [comment]
This is looking good in the develop branch!
thanks, MK

**Comment by birbjam** [comment]
ok will merge to master
