### ISSUE TITLE
map missing popup window content

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#76]
![Firefox_Screenshot_2020-06-25T02-31-42 119Z](https://user-images.githubusercontent.com/2523089/85646691-792fbf80-b651-11ea-8e8d-bc33a68a0080.png)
this could be a momentary fluke with the Team Geome widget or maybe not!

So putting this out there in case it belongs on the geomedb repo or if specific to the portal.

**Comment by birbjam** [comment]
Looks like this on my end as well.

**Comment by mkoo** [comment]
https://github.com/biocodellc/geome-ui/issues/490
