### ISSUE TITLE
Data discrepancy, possible errors?

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#77]
Summer intern Lizzy Pyle reported this discrepancy between charts and data in [this project](https://amphibiandisease.org/projects/?id=255).

Tallies for Craugaster ranoides do not match in the project barchart (145) and the downloaded xls (101).  See screenshots. 
![Screenshot (100)](https://user-images.githubusercontent.com/2523089/86846714-1fbb8d80-c060-11ea-9e2f-646f9dab40ed.png)
![Screenshot (101)](https://user-images.githubusercontent.com/2523089/86846732-24804180-c060-11ea-96be-8b67a75e3e66.png)

Also weird is the species piecharts: why is one sample for Bsal shown? is there another project associated here but not listed? https://amphibiandisease.org/dashboard/?id=Craugastor+ranoides
![Screenshot (97)](https://user-images.githubusercontent.com/2523089/86846856-47125a80-c060-11ea-8274-5d32c562cee3.png)

Perhaps rerun the API scripts since the 145 value is in the JSON right now, needs to be refreshed as a first step to troubleshoot?

**Comment by mkoo** [comment]
This seems relevant to this issue:
Species detail pages are not listing ALL contributing projects, although piecharts seems to be displaying all data for a given species.

An example:
https://amphibiandisease.org/dashboard/?id=Taricha+rivularis
should show:
 - [Pathogen invasion and non-epizootic dynamics in Pacific newts in California over the last century](https://amphibiandisease.org/projects/?id=244)
 - [USGS National Survey for the Amphibian Chytrid Fungus Batrachochytrium salamandrivorans](https://amphibiandisease.org/projects/?id=292)
It only lists the first project

Does this in both branches (dev and prod)

**Comment by birbjam** [comment]
The projects are being populated from [this API call](https://github.com/BNHM/AmphibiaWebDiseasePortalAPI/blob/master/data/scientificName_listing.json).

It lists one project associated with Taricha rivularis so it looks like that the API is still not automatically updating?
<img width="895" alt="Screen Shot 2020-07-08 at 1 21 12 PM" src="https://user-images.githubusercontent.com/41635757/86966502-227cb800-c11e-11ea-836f-b7ca5465af8d.png">

**Comment by birbjam** [comment]
Also for https://amphibiandisease.org/dashboard/?id=Craugastor+ranoides
It looks like there was one sample of Bsal tested but it tested negative.
[From this API call]:(https://github.com/BNHM/AmphibiaWebDiseasePortalAPI/blob/master/data/scientificName_diseaseDetected_Bsal.json)
<img width="528" alt="Screen Shot 2020-07-08 at 1 30 12 PM" src="https://user-images.githubusercontent.com/41635757/86967312-54dae500-c11f-11ea-9eb5-6ae3151f6f33.png">

**Comment by mkoo** [comment]
ok good to see that but why is it not included in the dataset XLSX
downloaded from ADP?

appears the XLSX is only for Bd tests?

**Comment by birbjam** [comment]
I'm not sure, should we open an issue in GEOME?

**Comment by mkoo** [comment]
yep, in more than one downloaded XLSX from a project page (eg https://amphibiandisease-develop.netlify.app/projects/?id=246) only see bd data (possibly)

**Comment by mkoo** [comment]
@jdeck88 is this a geome issue or can you see something obvious that we are missing?

Main issue is still that the API and charts show Craugaster ranoides has 145 but when you download XLSX there are only 101 and only Bd data (no Bsal). Why does a 44 count discrepancy exist?

**Comment by jdeck88** [comment]
Fixed a bug in the API see commit at:
https://github.com/BNHM/AmphibiaWebDiseasePortalAPI/commit/cf1d9432e6dc9f053a214ce1182f19c59e805da6

This fixes most of whats on this thread so closing.

BTW... The comment about Taricha rivularis belonging in two projects is a different issue.  That only exists in one GEOME project.  There is another rivularis in another project but genus is listed as Isthmohyla.
