### ISSUE TITLE
Request to include Back to Species list button on species detail page

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#85]
yes, I am lazy and now takes an extra 1-2 clicks to return to my spot on the species list browser.

It may be part of the answer but the current List by Species is not a stateful URL, ie., https://amphibiandisease.org/dashboard/#sort-k only brings you the Dashboard home page, not the K's on the List by Species.

**Comment by birbjam** [comment]
ha. i noticed this too and it also annoys me so its on my list

**Comment by mkoo** [comment]
yay for laziness!

**Comment by birbjam** [comment]
Individual tabs can be accessed at `dashboard/?tab=table-tab`. Pushed to develop.
"Back to Dashboard" button in species detail page takes user back to Species List.

Note: When user first lands on `/dashboard`, nothing but the button tabs is shown. I can change that, if we still want the default view to be tables.

Will work on accessing list sorting via URL.
