### ISSUE TITLE
charts not behaving in incognito window, maybe also in Chrome

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#91]
charts on species pages are not consistently appearing, depending on browser (I know a pain so at least we should give guidance)

- FF, incognito windows, species charts are blank (eg https://amphibiandisease.org/dashboard/?id=Hyliola+regilla)
-Chrome (v 84.0), in both incognito and regular windows, the species charts are not loading

I see consistently a js script not loading and JSON not parsing when inspecting the console!

**Comment by birbjam** [comment]
ah yeah it's because its trying to get data from localStorage and since its incognito, there is nothing stored locally until you go into Projects. this should be an easy fix.

**Comment by birbjam** [comment]
Should be working now in develop.
