### ISSUE TITLE
Make Tables default Dashboard view

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#94]
Hey @birbjam you wrote:
"Note: When user first lands on /dashboard, nothing but the button tabs is shown. I can change that, if we still want the default view to be tables."

Please make tables default! (already got one person telling me that the dashboard is broken....!)

**Comment by birbjam** [comment]
Ok got it. (Pushed to master)

**Comment by mkoo** [comment]
thanks!
